_core:
  default_config_hash: hSAUW7BoAd9YUpKcVKyZpW4wY67g4XZAYlt3Vnz6SVA
langcode: ca
enable_globally: null
enable_globally_on_admin_routes: false
default_challenge: image_captcha/Image
description: ''
title: CAPTCHA
administration_mode: false
administration_mode_on_admin_routes: false
whitelist_ips: ''
wrong_captcha_response_message: 'La resposta que heu introduït per al CAPTCHA és incorrecta.'
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: true
