_core:
  default_config_hash: PBJAPRAqH-w00jAUXbD9qV6frVT38tI1oXZiBIjV8gU
image_captcha_fonts_preview_map_cache:
  984e950858126332ff4905c76efeb723ee1aa185c07f80537ce57c26be1cc0c5:
    uri: modules/captcha/image_captcha/fonts/Tesox/tesox.ttf
    filename: tesox.ttf
    name: tesox
  ced5d84285b76ebcaa40beb0b5c0efc54aca6a6d347da73638673906d5cda331:
    uri: modules/captcha/image_captcha/fonts/Tuffy/Tuffy_Bold.ttf
    filename: Tuffy_Bold.ttf
    name: Tuffy_Bold
  3438abc85ac58eaab01cd741b1c3f9bb5dd3b9be3c079b1a7851884135608b2f:
    uri: modules/captcha/image_captcha/fonts/Tuffy/Tuffy.ttf
    filename: Tuffy.ttf
    name: Tuffy
image_captcha_fonts:
  - 986462a9e165423b12587d83a363091b837f54db5d7337cb3da3f97f54104fbb
  - 3dbed886c81a681a313bc6297f53db5699401194490d38621f05c7bdf06cf1f5
image_captcha_font_size: 30
image_captcha_character_spacing: '1.2'
image_captcha_image_allowed_chars: aAbBCdEeFfGHhijKLMmNPQRrSTtWXYZ23456789
image_captcha_code_length: 5
image_captcha_rtl_support: 0
image_captcha_background_color: '#ffffff'
image_captcha_foreground_color: '#000000'
image_captcha_foreground_color_randomness: 150
image_captcha_file_format: 1
image_captcha_distortion_amplitude: 5
image_captcha_bilinear_interpolation: 0
image_captcha_dot_noise: 1
image_captcha_line_noise: 1
image_captcha_noise_level: 1
